/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Imagenes.CargarImagenes;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;


/**
 *
 * @author jdavi
 */
public class MainView extends javax.swing.JFrame {

    DeteccionView DetectForm;
    CorreccionView CorrectForm;
    public Map<String, String> charAsciiHashMap = new HashMap<String, String>();
    public Map<String, String> asciiCharHashMap = new HashMap<String, String>();
    /**
     * Creates new form Main
     */
    public MainView() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        CorrectForm = new CorreccionView(this);
        DetectForm = new DeteccionView(this);
        Deteccion.setIcon(new ImageIcon(CargarImagenes.class.getResource("DetectIcon.png")));
        Correccion.setIcon(new ImageIcon(CargarImagenes.class.getResource("CorrectIcon.png"))); 
        this.setIconImage(new ImageIcon(CargarImagenes.class.getResource("ICON.png")).getImage());
        String[] Letters= {" " ,"." ,"," ,";" ,":" ,"A" ,"B" ,"C" ,"D" ,"E" ,"F" ,"G" ,"H" ,"I" ,"J" ,"K" ,"L" ,"M" ,"N" ,"Ñ"  ,"O" ,"P" ,"Q" ,"R" ,"S" ,"T" ,"U" ,"V" ,"W" ,"X" ,"Y" ,"Z" ,"a" ,"b" ,"c" ,"d"  ,"e"  ,"f"  ,"g"  ,"h"  ,"i"  ,"j"  ,"k"  ,"l"  ,"m"  ,"n"  ,"ñ"  ,"o"  ,"p"  ,"q"  ,"r"  ,"s"  ,"t"  ,"u"  ,"v"  ,"w"  ,"x"  ,"y"  ,"z" ,};
        String[] asciiVec={"32","46","44","59","58","65","66","67","68","69","70","71","72","73","74","75","76","77","78","165","79","80","81","82","83","84","85","86","87","88","89","90","97","98","99","100","101","102","103","104","105","106","107","108","109","110","164","111","112","113","114","115","116","117","118","119","120","121","122"};
        int k=0;
        for (String item : Letters){
            charAsciiHashMap.put(item,asciiVec[k]);
            asciiCharHashMap.put(asciiVec[k], item);
            k++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Correccion = new javax.swing.JButton();
        Deteccion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 350));
        setType(java.awt.Window.Type.POPUP);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Metodos de \"Correccion\" y \"Deteccion\" de errores");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Laboratorio");

        Correccion.setText("Correccion");
        Correccion.setBorder(null);
        Correccion.setBorderPainted(false);
        Correccion.setContentAreaFilled(false);
        Correccion.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        Correccion.setFocusPainted(false);
        Correccion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Correccion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Correccion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Correccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreccionActionPerformed(evt);
            }
        });

        Deteccion.setText("Deteccion ");
        Deteccion.setToolTipText("");
        Deteccion.setBorder(null);
        Deteccion.setBorderPainted(false);
        Deteccion.setContentAreaFilled(false);
        Deteccion.setFocusPainted(false);
        Deteccion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Deteccion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Deteccion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Deteccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeteccionActionPerformed(evt);
            }
        });

        jLabel3.setText("Jonathan ilias");

        jLabel4.setText("Steven Iglesias");
        jLabel4.setToolTipText("");

        jLabel5.setText("Martin Galvis");

        jLabel6.setText("Luis Garcia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(Correccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Deteccion)
                .addGap(104, 104, 104))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel3)
                        .addGap(175, 175, 175)
                        .addComponent(jLabel5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(300, 300, 300)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(167, 167, 167)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Deteccion)
                    .addComponent(Correccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeteccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeteccionActionPerformed
        DetectForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DeteccionActionPerformed

    private void CorreccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreccionActionPerformed
        CorrectForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CorreccionActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Correccion;
    private javax.swing.JButton Deteccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
